<?php echo $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml" lang="en">

<head>

<?php echo $this->headTitle() ?>
<?php echo $this->headMeta() ?>
<?php echo $this->headScript() ?>
<?php echo $this->headLink() ?>

</head>

<body>

<div id="layout-wrapper">
	<div id="layout-header">
		<p>Myqron</p>
		<ul>
			<li><a href="/" title="<?php echo $this->translate('Home') ?>"><?php echo $this->translate('Home') ?></a></li>
			<?php if ($this->identity === null): ?>
			<li><a href="<?php echo $this->url(array(), 'login') ?>" title="<?php echo $this->translate('Login') ?>"><?php echo $this->translate('Login') ?></a></li>
			<li><a href="<?php echo $this->url(array(), 'register') ?>" title="<?php echo $this->translate('Register') ?>"><?php echo $this->translate('Register') ?></a></li>
			<?php else: ?>
			<li><a href="<?php echo $this->url(array('id' => $this->identity->id), 'user') ?>" title="<?php echo $this->translate('Profile') ?>"><?php echo $this->translate('Profile') ?></a></li>
			<li><a href="<?php echo $this->url(array(), 'logout') ?>" title="<?php echo $this->translate('Logout') ?>"><?php echo $this->translate('Logout') ?></a></li>
			<?php endif; ?>
		</ul>
	</div>
	<div id="layout-content" class="clearfix">
		<?php echo $this->layout()->content ?>
	</div>
	<div id="layout-footer">
		<ul>
			<li><a href="/wiki" title="Wiki">Wiki</a></li>
		</ul>
	</div>
</div>

</body>

</html>