<h1><?php echo $this->escape($this->application->name) ?></h1>

<ul>
	<li><a href="<?php echo $this->url(array('id' => $this->identity->id), 'user') ?>" title="<?php echo $this->translate('Back to my profile') ?>"><?php echo $this->translate('Back to my profile') ?></a></li>
</ul>

<h2>Edit</h2>

<div class="form">
	<?php echo $this->form ?>
</div>

<h2><?php echo $this->translate('Templates') ?></h2>

<?php if (sizeof($this->templates) == 0): ?>
<p><?php echo $this->translate('You haven\'t defined any templates for this application yet.') ?></p>
<?php else: ?>
<table>
	<tr>
		<th><?php echo $this->translate('ID') ?></th>
		<th><?php echo $this->translate('Name') ?></th>
		<th><?php echo $this->translate('Flags') ?></th>
		<th><?php echo $this->translate('Body') ?></th>
	</tr>
	<?php foreach ($this->templates as $template): ?>
	<tr>
		<td><?php echo $template->id ?></td>
		<td><a href="<?php echo $this->url(array('id' => $template->id), 'template') ?>" title="<?php echo $this->translate('Edit') ?>"><?php echo $this->escape($template->name) ?></a></td>
		<td>
			<?php if ($template->privacy == 'private'): ?>
			<img src="/www/img/icons/private.png" alt="<?php echo $this->translate('Private') ?>" title="<?php echo $this->translate('Private') ?>" />
			<?php else: ?>
			<?php if ($template->web_hooks == 'yes'): ?>
			<img src="/www/img/icons/web-hooks.png" alt="<?php echo $this->translate('Web hooks') ?>" title="<?php echo $this->translate('Web hooks') ?>" />
			<?php endif; ?>
			<?php endif; ?>
		</td>
		<td><?php echo $this->formatText($template->body) ?></td>
	</tr>
	<?php endforeach; ?>
</table>
<?php endif; ?>

<ul>
	<li><a href="<?php echo $this->url(array(), 'template-new') ?>?applicationid=<?php echo $this->application->id ?>" title="<?php echo $this->translate('Create an event template') ?>"><?php echo $this->translate('Create an event template') ?></a></li>
</ul>

<h2>Events</h2>

<?php if (sizeof($this->events) == 0): ?>
<p><?php echo $this->translate('No events have been submitted for this application.') ?></p>
<?php else: ?>
<table>
	<tr>
		<th><?php echo $this->translate('ID') ?></th>
		<th><?php echo $this->translate('Template') ?></th>
		<th><?php echo $this->translate('Content') ?></th>
		<th><?php echo $this->translate('Time') ?></th>
	</tr>
	<?php foreach ($this->events as $event): ?>
	<?php $template = $event->findParentRow('Shared_Db_Table_Template') ?>
	<tr>
		<td><?php echo $event->id ?></td>
		<td><?php echo $this->escape($template->name) ?></td>
		<td><?php echo $this->parseTemplate(
			$template->body,
			$event->findDependentRowset('Shared_Db_Table_Token')
		) ?></td>
		<td><?php echo $event->created ?></td>
	</tr>
	<?php endforeach; ?>
</table>
<?php endif; ?>